config/routes.rb
CouponCorner::Application.routes.draw do

  resources :categories

  resources :line_items

  get "users/new"

  get "pages/home"
  get "pages/about_us"
  get "pages/sign_up"
  get "pages/thank_you"
  get "pages/client_sign_up"

  resources :coupons do
    collection do
      post :show_multiple
    end
  end

  resources :users
  resources :sessions
  resources :client, :controller => :users

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  root :to => "pages", :action => "home"

end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  has_many :coupons
  has_many :orders

  attr_accessor :password
  before_save :encrypt_password

  validates :email,
            :uniqueness => true,
            :length => {:within => 5..50},
            :format => {:with =>
                            /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
  validates :password,
            :confirmation => true,
            :length => {:within => 4..20},
            :presence => true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.authenticated?(password)
      user.update_attribute(:last_login, DateTime.now())
      return user
    end
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password + "ruby_rocks" + self.salt)
  end

  protected

  def encrypt_password
    return if password.blank?
    salt = generate_salt
    self.hashed_password = encrypt(password + "ruby_rocks" + salt)
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end
  def generate_salt
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    salt = ""
    1.upto(10) { |i| salt << chars[rand(chars.size-1)] }
    self.salt = salt
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :except => [:create]

  def new
    @user = User.new
    #Client.create(:name,:password )
  end

  def create
    @user = User.new(params[:user])
    #@user.type = "Client"
    @user.last_login = DateTime.now()
      if @user.save
        if current_user and current_user.admin
          redirect_to users_path, :notice => 'User creation successful!'
        else
          session[:user_id.to_s] = @user.id
          redirect_to coupons_path, :notice => 'User creation successful!'
        end
      #elsif @user.save.type == "Client"
        #session[:client_id.to_s] = @user.id

      else
        render :action => 'new', :notice => 'User creation failed!'
      end
  end

  def authenticate
    unless User.find_by_id(session[:user_id.to_s])
      redirect_to login_url, :notice => "Please log in"
    end
  end

  def index
    redirect_to(root_url) unless current_user.admin
    @users = User.all
  end

  def edit
    return unless (params[:id] = current_user.id.to_s()) or current_user.admin
    @user = User.find(params[:id])
  end

  def show
    return unless (params[:id] == current_user.id.to_s()) or current_user.admin
    @user = User.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        @user.email = params[:email]
        @user.password = params[:password]
        #@user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User details were successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    return unless current_user.admin?
    @user = User.find(params[:id])
    @user.destroy
    flash[:success] = "User deleted."

    respond_to do |format|
      format.html { redirect_to(users_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
    <% if @user.errors.any? %>
        <div id="errorExplanation">
          <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>
          <ul>
            <% @user.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      <%= f.label :email %><br />
      <%= f.text_field :email %>
    </div>

    <div class="field">
      <%= f.label :password %><br />
      <%= f.password_field :password %>
    </div>
    <div class="actions">
      <%= f.submit "Submit details"%>
    </div>
<% end %>

app/views/users/edit.html.erb
<%= stylesheet_link_tag 'bootstrap' %>

<h1>Editing account details</h1>

<%= render 'form' %>

<%= link_to 'Show details', @user %> |
<%= link_to 'Back', @user %>

app/views/users/index.html.erb
<%= stylesheet_link_tag 'bootstrap' %>
<h1 align="center">Listing Users</h1>

<table class = "table" width="980" border="1">
  <tr>
    <th>Email</th>
    <th>Admin</th>
    <th>User Type</th>
    <th></th>
    <th></th>
  </tr>

  <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.admin %></td>
        <td><%= user.type %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete,
                        data: { confirm: "Are you sure?" } %></td>
      </tr>
  <% end %>

</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<%= stylesheet_link_tag 'bootstrap' %>
<h1 align class="center">Create User</h1>
<div class = "form" align = "center" >
<%= render 'form' %>
</div>

app/views/users/show.html.erb
<%= stylesheet_link_tag 'bootstrap' %>
<p id="notice"><%= notice %></p>

<p>
  <h3>Welcome <%= @user.email %> </h3>
</p>


<p>
  <h5>Your Last Login was <%= @user.last_login.inspect %> </h5>
</p>



<li class="active"><%= link_to 'Edit your account details', edit_user_path(@user) %></li>

<p>
    <% if current_client %>
        <li class="active"><%= link_to "Input new Coupon details", new_coupon_path %></li>
    <% end %>
</p>

<!--<table>-->
  <!--<tr>-->
    <!--<th>Name</th>-->
    <!--<th>Address</th>-->
    <!--<th>Email</th>-->
    <!--<th>Pay type</th>-->
    <!--<th></th>-->
    <!--<th></th>-->
    <!--<th></th>-->
  <!--</tr>-->


<!--</table>-->

</br>
</br>
</br>