config/routes.rb
CouponCorner::Application.routes.draw do

  resources :categories

  resources :line_items

  get "users/new"

  get "pages/home"
  get "pages/about_us"
  get "pages/sign_up"
  get "pages/thank_you"
  get "pages/client_sign_up"

  resources :coupons do
    collection do
      post :show_multiple
    end
  end

  resources :users
  resources :sessions
  resources :client, :controller => :users

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"

  root :to => "pages", :action => "home"

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :user

  belongs_to :category, counter_cache:true
  #attr_accessible :name, :price, :category_id

  has_many :line_items

  #paperclip
  has_attached_file :Brand_image,
                    :styles => {:thumb => "40x40", :small => "150x150"} ,
                    :default_url => "/images/:Brand_image.png"


  def self.search(search_query)
    if search_query
      find(:all,:conditions => ['name LIKE ?', "%#{ search_query}%"])
    else
      find(:all)
    end
  end

  #def image_file=(input_data)
   # self.filename = input_data.original_filename
    #self.content_type = input_data.content_type.chomp
    #self.binary_data = input_data.read
  #end
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  has_many :coupons
  has_many :orders

  attr_accessor :password
  before_save :encrypt_password

  validates :email,
            :uniqueness => true,
            :length => {:within => 5..50},
            :format => {:with =>
                            /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i}
  validates :password,
            :confirmation => true,
            :length => {:within => 4..20},
            :presence => true

  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.authenticated?(password)
      user.update_attribute(:last_login, DateTime.now())
      return user
    end
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password + "ruby_rocks" + self.salt)
  end

  protected

  def encrypt_password
    return if password.blank?
    salt = generate_salt
    self.hashed_password = encrypt(password + "ruby_rocks" + salt)
  end

  def encrypt(string)
    Digest::SHA1.hexdigest(string)
  end
  def generate_salt
    chars = ("a".."z").to_a + ("A".."Z").to_a + ("0".."9").to_a
    salt = ""
    1.upto(10) { |i| salt << chars[rand(chars.size-1)] }
    self.salt = salt
  end
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  # GET /coupons
  # GET /coupons.xml
  before_filter :authenticate, :except => [:index, :show]

  def index
    @coupon = Coupon.search(params[:search_query])
    #@coupon.category_id.(params[:category_id])
    if params[:category_id]
      category =  Category.find(params[:category_id])
      @coupon = category.coupons
    else
      @coupons = Coupon.all
    end
    #@categories = Category.all


    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

  # GET /coupons/1
  # GET /coupons/1.xml
  def show
    @coupon = Coupon.find(params[:id])


    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

  # GET /coupons/new
  # GET /coupons/new.xml
  def new
    @coupon = Coupon.new
    @categories = Category.all

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @coupon }
    end
  end

  # GET /coupons/1/edit
  def edit
    @coupon = Coupon.find(params[:id])
    @categories = Category.all
  end

  # POST /coupons
  # POST /coupons.xml
  def create
    return unless current_user.admin or current_client
    @coupon = current_user.coupons.new(params[:coupon])

    respond_to do |format|
      if @coupon.save
        format.html { redirect_to(@coupon, :notice => 'coupon was successfully created.') }
        format.xml  { render :xml => @coupon, :status => :created, :location => @coupon }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /coupons/1
  # PUT /coupons/1.xml
  def update
    return unless current_user.admin
    @coupon = Coupon.find(params[:id])

    respond_to do |format|
      if @coupon.update_attributes(params[:coupon])
        @coupon.Brand_name = params[:Brand_name]
        @coupon.Offer_desc = params[:Offer_desc]
        @coupon.Saving_amount = params[:Saving_amount]
        #@categories = Category.all
        @coupon.category_id = params[:category_id]
        @coupon.Start_date = params[:Start_date]
        @coupon.Expiry_date = params[:Expiry_date]
        @coupon.Client_details = params[:Client_details]
        @coupon.Barcode_no = params[:Barcode_no]
        @coupon.update_attributes(params[:coupon])

        format.html { redirect_to(@coupon, :notice => 'Coupon was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @coupon.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /coupons/1
  # DELETE /coupons/1.xml
  def destroy
    @coupon = Coupon.find(params[:id])
    @coupon.destroy

    flash[:success] = "User deleted."

    respond_to do |format|
      format.html { redirect_to(coupons_url) }
      format.xml  { head :ok }
    end
  end

  #def display
  #  @ids = []
   # params[:display].each do |key, val|
    #  if val != "0"
     #   @ids << key
      #end
    #end
    #render 'display'
  #end

  def show_multiple

    @coupon = Coupon.find(params[:coupon_ids])
  end



end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/views/coupons/_form.html.erb
<%= stylesheet_link_tag "bootstrap.css" %>
<%= form_for @coupon, :html => { :multipart => true } do |f| %>
    <% if @coupon.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

          <ul>
            <% @coupon.errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :Brand_name %>
      <%= f.text_field :Brand_name %>
    </div><br />

    <!--<div class="field">-->
    <%= form_for (@coupon), :url=>{:action=>'create'}, :html=>{:multipart=>true} do |form| %><br/>
        <!--<%= form.label :Brand_image %>-->
        <!--<%= form.file_field :image_file %>-->
        <!--<%= form.submit %>-->
        <!--<% end %>-->
    <!--</div>-->
    <!--upload image using paperclip -->
    <div class="field">
        <%= f.label :Coupon_image %>
        <%= f.file_field :Brand_image%>
    </div><br/><br/>

    <div class="field">
      <%= f.label :Offer_desc %>
      <%= f.text_area :Offer_desc, rows: 6 %>
    </div><br />

    <div class="field">
      <%= f.label :Saving_amount %>
      <%= f.text_field :Saving_amount %>
    </div><br />

    <div class="field">
      <%= f.label :category_name %>
      <%= collection_select(:coupon, :category_id, @categories, :id, :name, {:prompt => false })  %>
    </div>   <br />

    <div class="field">
      <%= f.label :Start_date %>
      <%= f.date_select :Start_date %>
    </div><br />

    <div class="field">
      <%= f.label :Expiry_date %>
      <%= f.date_select :Expiry_date %>
    </div> <br />

    <div class="field">
      <%= f.label "Consumers & Retailers details" %>
      <%= f.text_area :Client_details, rows: 6 %>
    </div><br />

    <div class="field">
      <%= f.label "Client Coupon Redemption details" %>
      <%= f.text_area :redemption_details, rows: 6 %>
    </div><br />

    <div class="field">
      <%= f.label :Barcode_no %>
      <%= f.number_field :Barcode_no %>
    </div> <br />

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/coupons/display.html.erb
<%= form_tag 'display' %>
<p id="notice"><%= notice %></p>

<p>
  <b>Brand name:</b>
  <%= @coupon.Brand_name %>
</p>

<p>
  <b>Brand image:</b>
  <%= @coupon.Brand_image %>
</p>

<p>
  <b>Offer desc:</b>
  <%= @coupon.Offer_desc %>
</p>

<p>
  <b>Saving amount:</b>
  <%= @coupon.Saving_amount %>
</p>

<p>
  <b>Category:</b>
  <%= @coupon.Category %>
</p>

<p>
  <b>Coupon image:</b>
  <%= @coupon.Coupon_image %>
</p>

<p>
  <b>Start date:</b>
  <%= @coupon.Start_date %>
</p>

<p>
  <b>Expiry date:</b>
  <%= @coupon.Expiry_date %>
</p>

<p>
  <b>Client details:</b>
  <%= @coupon.Client_details %>
</p>

<p>
  <b>Barcode no:</b>
  <%= @coupon.Barcode_no %>
</p>


<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/edit.html.erb
<%= stylesheet_link_tag "bootstrap.css" %>
<h1>Editing coupon</h1>

<%= render 'form' %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>
<%= image_tag(@coupon.image_url)%>

app/views/coupons/index.html.erb
<%= stylesheet_link_tag "bootstrap.css" %>

<h1 align="center">Want to Save Money on your Weekly Grocery shop?</h1>
<h3 align="center"><strong>Browse our Coupon Gallery</strong></h3>
<!--<p>-->
      <!--<%= text_field_tag :search_query, params[:search_query] %>-->
      <!--<%= submit_tag "Search", :name => nil %>-->
    <!--</p>-->

<%= form_tag('/coupons',:method=>:get) do %>
<h5>Category Search</h5></p><%= select_tag "category_id", options_from_collection_for_select(Category.all, "id", "name",params[:category_id])%>
<%= submit_tag "Search" %>
<% end %>
<%= form_tag show_multiple_coupons_path do %>
<p align="right"><% if current_client %>
        <a class="small blue signup button" text-color = "#ffffff" text-size = "11px" tabindex="7" href=<%= link_to "Input new Coupon", new_coupon_path %></a>
    <% end %>
</p>
<p align="right"><%= submit_tag "Show selected coupons" %>
 <table class = "table" width="980" height="305" border="2">
  <tr border = "3">
    <th scope="col">Brand</th>
    <th scope="col">Brand Image</th>
    <th scope="col">Category</th>
    <th scope="col">Offer Description</th>
    <th scope="col">Saving Amount</th>
    <th scope="col">Select a Coupon</th>

    </th>
  </tr>

  <% for coupon in @coupon %>

      <tr>
        <td><p align="center"><%= coupon.Brand_name %></p></td>
        <td><p align="center">
          <%= image_tag coupon.Brand_image.url(:thumb) %>
          <!--<%= image_tag(coupon.Brand_image, :size => "100x100", class: 'list_Brand_image')%>  -->
        </p>
        </td>

        <td><p align="center"><%= coupon.category.name %></p></td>


        <td>
          <p align="center">
              <%= coupon.Offer_desc %>
          </p>
        </td>
        <td><p align="center"><%= number_to_currency coupon.Saving_amount, :unit => "&euro;" %></p></td>
        <!--<td><img src="<%= barcode_image_uri(coupon.Barcode_no.to_s)unless coupon.Barcode_no.to_s.nil? %>"/></td>-->
        <!--<td><%= coupon.user_id.to_s %></td>-->
        <td><p align="center"><%= check_box_tag("coupon_ids[]", coupon.id) %></p></td>


        <!--<td><%= link_to 'Show', coupon %></td>-->
        <!--<td><%= coupon.Category %></td>-->
        <!--<td><%= coupon.Coupon_image %></td>-->
        <!--<td><%= coupon.Start_date %></td>-->
        <!--<td><%= coupon.Expiry_date %></td>-->
        <!--<td><%= coupon.Client_details %></td>-->
        <!--<td><%= coupon.Barcode_no %></td>-->
        <td>
          <% if current_user and current_user.admin %>
            <td><p align="center"><%= link_to 'Show', coupon %></p></td>
            <td><p align="center"><%= link_to 'Edit', edit_coupon_path(coupon) %></p></td>
            <td><p align="center"><%= link_to 'Destroy', coupon, :confirm => 'Are you sure?', :method => :delete %></p></td>
        <% end %>
        <!--<td><%= button_to 'Add to Coupon Selection', line_items_path(:coupon_id => coupon) %></td>-->
        </td>
      </tr>
  <% end %>
</table>
<p align = "right"><%= submit_tag "Show selected coupons" %></p>
<br />
<% if current_user and current_user.admin? %>
<%= link_to 'New Coupon', new_coupon_path %>

    <% end %>



<% end %>

app/views/coupons/new.html.erb
<%= stylesheet_link_tag 'bootstrap' %>
<h1>New Coupon</h1>

<%= render 'form' %>

<%= link_to 'Back', coupons_path %>

app/views/coupons/show.html.erb
<%= stylesheet_link_tag "bootstrap.css" %>
<p id="notice"><%= notice %></p>

<p>
  <b>Brand name:</b>
  <%= @coupon.Brand_name %>
</p>

<p>
  <b>Brand image:</b>
  <%= @coupon.Brand_image %>
</p>

<p>
  <b>Offer desc:</b>
  <%= @coupon.Offer_desc %>
</p>

<p>
  <b>Saving amount:</b>
  <%= @coupon.Saving_amount %>
</p>

<p>
  <b>Category:</b>
  <%= @coupon.category.name %>
</p>

<p>
  <b>Coupon image:</b>
  <%= @coupon.Coupon_image %>
</p>

<p>
  <b>Start date:</b>
  <%= @coupon.Start_date %>
</p>

<p>
  <b>Expiry date:</b>
  <%= @coupon.Expiry_date %>
</p>

<p>
  <b>Client details:</b>
  <%= @coupon.Client_details %>
</p>

<p>
  <b>Barcode no:</b>
  <%= @coupon.Barcode_no %>
</p>


<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>

app/views/coupons/show_multiple.html.erb
<link rel="stylesheet" href="assets/stylesheets/bootstrap.css" media="screen">

<% stylesheet_link_tag 'print', :media => "print" %>

<SCRIPT language=JavaScript>
    <!-- http://www.spacegun.co.uk -->
    var message = "right click disabled";
    function rtclickcheck(keyp){ if (navigator.appName == "Netscape" && keyp.which == 3){ 	alert(message); return false; }
        if (navigator.appVersion.indexOf("MSIE") != -1 && event.button == 2) { 	alert(message); 	return false; } }
    document.onmousedown = rtclickcheck;
</SCRIPT>


<% for coupon in @coupon %>

            <%= hidden_field_tag "coupons_ids[]", coupon.id%>


          <a class="small blue signup button" href="#" onclick="window.print();return false;"><span class = "sign-up">Print Coupon/s</span></a>

  <table style="margin: 10px 0 10px 25px; border: 2px dashed #0a79bF; border-collapse: collapse;">
      <tr>
        <td width="600" height="68">
          <table width="600" cellspacing="0" cellpadding="0" bordercolor="#67BEE9" border="1" style="border-collapse: collapse;">				<tr>
            <td width="227" height="65" style="width: 100px;"><a href="Main Page.html"><%= image_tag "CCLogo2sml.png", :size => "200x100", :alt => "logo" %></a></td>
            <td width="367" class="cpntext" style="width: 318px; vertical-align: middle; font-size: 8px; padding: 0; font-family: Verdana, Geneva, sans-serif;"><strong>TO THE CASHIER:</strong> VALID AGAINST EXACT PRODUCT ONLY. VERIFY CONSUMER HAS PRODUCT IN BASKET BEFORE ACCEPTING.&nbsp;&nbsp;&nbsp;&nbsp;PBQ ID: 0157 2074</td>
          </tr>
          </table>
        </td>
      </tr>
      <tr>
      <td width="600">
        <table width="598" cellspacing="0" cellpadding="0" bordercolor="#67BEE9" border="1">
          <tr>
            <td>
              <table width="596" cellspacing="0" cellpadding="0" border="0">
                <tr>
                  <td style="padding-top: 3px; vertical-align: top; width: 160px;">
                    <table width="153" cellspacing="0" cellpadding="0" border="0">
                      <tbody>
                      <tr>
                        <td style="padding-left: 3px;">
                          <%= image_tag(coupon.Brand_image, class: 'list_Brand_image')%>
                        </td>
                      </tr>
                      </tbody>
                    </table>
                  </td>
                  <td style="padding-top: 3px; vertical-align: top; width: 420px;">
                    <table cellspacing="0" cellpadding="0" border="0" style="width: 100%; font-family: Verdana, Geneva, sans-serif;">
                      <tr>
                        <td colspan="3" class="cpntext" style="font-weight: bold; text-align: center; font-size: 12px;">
                          <table style="width: 90%; margin: auto; border-bottom: 1px dashed gray; border-collapse: collapse; font-size: 10px;" cellpadding="2">
                            <tr>
                              <td style="width: 33%; text-align: left;">Valid To: <%= l (coupon.Expiry_date), :format => :default %></td>
                              <td style="width: 34%; text-align: center;">Email: <% if logged_in? %><%= current_user.email %><%end %></td>
                              <td style="width: 33%; text-align: right;">SecurityID: <%= coupon.user_id %></td>
                            </tr>
                          </table>
                        </td>
                      </tr>
                      <tr>
                        <td colspan="3" style="padding-top: 10px; vertical-align: middle; font-size: 22px; text-align: center; padding-bottom: 10px;"><%= coupon.Offer_desc %></td>
                      </tr>
                      <tr>
                        <td colspan="3" class="cpntext" style="font-size: 9px; padding: 0px 5px 5px 5px;"><strong>Consumers &amp; Retailers: </strong><%= coupon.Client_details %>
                          <br>
                        </td>
                      </tr>
                      <tr>
                        <td style="text-align: left; vertical-align: top; width: 110px;">&nbsp;
                        </td>
                        <td valign="top" align="center" class="cpntext" style="width: 160px; padding-top: 10px;">
                          <div style="width: 160px;"><strong>REDEMPTION: </strong>
                            <%= coupon.redemption_details %>
                          </div>
                        </td>
                        <td style="vertical-align: top; text-align: right; font-size: 9px; width: 160px; padding-top: 5px;">
                          <div style="width: 160px; text-align: center; font-size: 8px; font-weight: bold;">Retailers scan here:
                          </div>
                          <div style="width: 160px;">
                            <div style="vertical-align: top; width: 150px; float: left;">
                              <img src="<%= barcode_image_uri(coupon.Barcode_no.to_s)unless coupon.Barcode_no.to_s.nil? %>"/><br/>
                              <%= coupon.Barcode_no %> <br/><br/>
                            </div>
                            <div style="vertical-align: top; display: inline; float: left; width: 10px;">
                            </div>
                            <div style="clear: both;">
                            </div>
                          </div>
                        </td>
                      </tr>
                      <tr>
                        <td colspan="3" style="vertical-align: middle; font-size: 8px; text-align: center;">For any questions or support, please contact coupons@coupon_corner.ie.
                        </td>
                      </tr>
                    </table>
                  </td>
                </tr>
              </table>
            </td>
          </tr>
        </table>
      </td>
      </tr>
    </table>

    <div style="border-bottom: 1px dashed black;">
    </div>
      <% end %>